language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "hpeng526"
  - git config user.email "hpeng526@gmail.com"
  - git add .
  - git commit -m "update"
  - git push --force --quite "http://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - src

env:
  global:
    - GH_REF: github.com/hpeng526/hpeng526.github.io.git