---
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config --local user.name "hpeng526"
  - git config --local user.email "hpeng526@gmail.com"
  - git add --all .
  - git commit -m "update"
  - git push -f https://$GH_TOKEN@github.com/hpeng526/hpeng526.github.io.git master

branches:
  only:
    - src