language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config --local user.name "hpeng526"
  - git config --local user.email "hpeng526@gmail.com"
  - git add --all .
  - git commit -m "update"
  - git push -f https://$GH_TOKEN@github.com/hpeng526/hpeng526.github.io.git master

branches:
  only:
    - src